// Code generated by ent, DO NOT EDIT.

package cloudinarycredential

import (
	"taskai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldUserID, v))
}

// CloudName applies equality check predicate on the "cloud_name" field. It's identical to CloudNameEQ.
func CloudName(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldCloudName, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldAPIKey, v))
}

// APISecret applies equality check predicate on the "api_secret" field. It's identical to APISecretEQ.
func APISecret(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldAPISecret, v))
}

// MaxFileSizeMB applies equality check predicate on the "max_file_size_mb" field. It's identical to MaxFileSizeMBEQ.
func MaxFileSizeMB(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldMaxFileSizeMB, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldStatus, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldLastError, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldUserID, vs...))
}

// CloudNameEQ applies the EQ predicate on the "cloud_name" field.
func CloudNameEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldCloudName, v))
}

// CloudNameNEQ applies the NEQ predicate on the "cloud_name" field.
func CloudNameNEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldCloudName, v))
}

// CloudNameIn applies the In predicate on the "cloud_name" field.
func CloudNameIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldCloudName, vs...))
}

// CloudNameNotIn applies the NotIn predicate on the "cloud_name" field.
func CloudNameNotIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldCloudName, vs...))
}

// CloudNameGT applies the GT predicate on the "cloud_name" field.
func CloudNameGT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldCloudName, v))
}

// CloudNameGTE applies the GTE predicate on the "cloud_name" field.
func CloudNameGTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldCloudName, v))
}

// CloudNameLT applies the LT predicate on the "cloud_name" field.
func CloudNameLT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldCloudName, v))
}

// CloudNameLTE applies the LTE predicate on the "cloud_name" field.
func CloudNameLTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldCloudName, v))
}

// CloudNameContains applies the Contains predicate on the "cloud_name" field.
func CloudNameContains(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContains(FieldCloudName, v))
}

// CloudNameHasPrefix applies the HasPrefix predicate on the "cloud_name" field.
func CloudNameHasPrefix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasPrefix(FieldCloudName, v))
}

// CloudNameHasSuffix applies the HasSuffix predicate on the "cloud_name" field.
func CloudNameHasSuffix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasSuffix(FieldCloudName, v))
}

// CloudNameEqualFold applies the EqualFold predicate on the "cloud_name" field.
func CloudNameEqualFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEqualFold(FieldCloudName, v))
}

// CloudNameContainsFold applies the ContainsFold predicate on the "cloud_name" field.
func CloudNameContainsFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContainsFold(FieldCloudName, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContainsFold(FieldAPIKey, v))
}

// APISecretEQ applies the EQ predicate on the "api_secret" field.
func APISecretEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldAPISecret, v))
}

// APISecretNEQ applies the NEQ predicate on the "api_secret" field.
func APISecretNEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldAPISecret, v))
}

// APISecretIn applies the In predicate on the "api_secret" field.
func APISecretIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldAPISecret, vs...))
}

// APISecretNotIn applies the NotIn predicate on the "api_secret" field.
func APISecretNotIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldAPISecret, vs...))
}

// APISecretGT applies the GT predicate on the "api_secret" field.
func APISecretGT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldAPISecret, v))
}

// APISecretGTE applies the GTE predicate on the "api_secret" field.
func APISecretGTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldAPISecret, v))
}

// APISecretLT applies the LT predicate on the "api_secret" field.
func APISecretLT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldAPISecret, v))
}

// APISecretLTE applies the LTE predicate on the "api_secret" field.
func APISecretLTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldAPISecret, v))
}

// APISecretContains applies the Contains predicate on the "api_secret" field.
func APISecretContains(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContains(FieldAPISecret, v))
}

// APISecretHasPrefix applies the HasPrefix predicate on the "api_secret" field.
func APISecretHasPrefix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasPrefix(FieldAPISecret, v))
}

// APISecretHasSuffix applies the HasSuffix predicate on the "api_secret" field.
func APISecretHasSuffix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasSuffix(FieldAPISecret, v))
}

// APISecretEqualFold applies the EqualFold predicate on the "api_secret" field.
func APISecretEqualFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEqualFold(FieldAPISecret, v))
}

// APISecretContainsFold applies the ContainsFold predicate on the "api_secret" field.
func APISecretContainsFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContainsFold(FieldAPISecret, v))
}

// MaxFileSizeMBEQ applies the EQ predicate on the "max_file_size_mb" field.
func MaxFileSizeMBEQ(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldMaxFileSizeMB, v))
}

// MaxFileSizeMBNEQ applies the NEQ predicate on the "max_file_size_mb" field.
func MaxFileSizeMBNEQ(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldMaxFileSizeMB, v))
}

// MaxFileSizeMBIn applies the In predicate on the "max_file_size_mb" field.
func MaxFileSizeMBIn(vs ...int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldMaxFileSizeMB, vs...))
}

// MaxFileSizeMBNotIn applies the NotIn predicate on the "max_file_size_mb" field.
func MaxFileSizeMBNotIn(vs ...int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldMaxFileSizeMB, vs...))
}

// MaxFileSizeMBGT applies the GT predicate on the "max_file_size_mb" field.
func MaxFileSizeMBGT(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldMaxFileSizeMB, v))
}

// MaxFileSizeMBGTE applies the GTE predicate on the "max_file_size_mb" field.
func MaxFileSizeMBGTE(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldMaxFileSizeMB, v))
}

// MaxFileSizeMBLT applies the LT predicate on the "max_file_size_mb" field.
func MaxFileSizeMBLT(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldMaxFileSizeMB, v))
}

// MaxFileSizeMBLTE applies the LTE predicate on the "max_file_size_mb" field.
func MaxFileSizeMBLTE(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldMaxFileSizeMB, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContainsFold(FieldStatus, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotNull(FieldLastCheckedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldContainsFold(FieldLastError, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CloudinaryCredential) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CloudinaryCredential) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CloudinaryCredential) predicate.CloudinaryCredential {
	return predicate.CloudinaryCredential(sql.NotPredicates(p))
}
