// Code generated by ent, DO NOT EDIT.

package emailprovider

import (
	"taskai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldProvider, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldAPIKey, v))
}

// SenderEmail applies equality check predicate on the "sender_email" field. It's identical to SenderEmailEQ.
func SenderEmail(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldSenderEmail, v))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldSenderName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldStatus, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldLastError, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldProvider, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldAPIKey, v))
}

// SenderEmailEQ applies the EQ predicate on the "sender_email" field.
func SenderEmailEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldSenderEmail, v))
}

// SenderEmailNEQ applies the NEQ predicate on the "sender_email" field.
func SenderEmailNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldSenderEmail, v))
}

// SenderEmailIn applies the In predicate on the "sender_email" field.
func SenderEmailIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldSenderEmail, vs...))
}

// SenderEmailNotIn applies the NotIn predicate on the "sender_email" field.
func SenderEmailNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldSenderEmail, vs...))
}

// SenderEmailGT applies the GT predicate on the "sender_email" field.
func SenderEmailGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldSenderEmail, v))
}

// SenderEmailGTE applies the GTE predicate on the "sender_email" field.
func SenderEmailGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldSenderEmail, v))
}

// SenderEmailLT applies the LT predicate on the "sender_email" field.
func SenderEmailLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldSenderEmail, v))
}

// SenderEmailLTE applies the LTE predicate on the "sender_email" field.
func SenderEmailLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldSenderEmail, v))
}

// SenderEmailContains applies the Contains predicate on the "sender_email" field.
func SenderEmailContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldSenderEmail, v))
}

// SenderEmailHasPrefix applies the HasPrefix predicate on the "sender_email" field.
func SenderEmailHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldSenderEmail, v))
}

// SenderEmailHasSuffix applies the HasSuffix predicate on the "sender_email" field.
func SenderEmailHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldSenderEmail, v))
}

// SenderEmailEqualFold applies the EqualFold predicate on the "sender_email" field.
func SenderEmailEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldSenderEmail, v))
}

// SenderEmailContainsFold applies the ContainsFold predicate on the "sender_email" field.
func SenderEmailContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldSenderEmail, v))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldSenderName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldStatus, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotNull(FieldLastCheckedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldContainsFold(FieldLastError, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailProvider {
	return predicate.EmailProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailProvider) predicate.EmailProvider {
	return predicate.EmailProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailProvider) predicate.EmailProvider {
	return predicate.EmailProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailProvider) predicate.EmailProvider {
	return predicate.EmailProvider(sql.NotPredicates(p))
}
