// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/emailprovider"
	"taskai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailProviderUpdate is the builder for updating EmailProvider entities.
type EmailProviderUpdate struct {
	config
	hooks    []Hook
	mutation *EmailProviderMutation
}

// Where appends a list predicates to the EmailProviderUpdate builder.
func (_u *EmailProviderUpdate) Where(ps ...predicate.EmailProvider) *EmailProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *EmailProviderUpdate) SetProvider(v string) *EmailProviderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableProvider(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *EmailProviderUpdate) SetAPIKey(v string) *EmailProviderUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableAPIKey(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSenderEmail sets the "sender_email" field.
func (_u *EmailProviderUpdate) SetSenderEmail(v string) *EmailProviderUpdate {
	_u.mutation.SetSenderEmail(v)
	return _u
}

// SetNillableSenderEmail sets the "sender_email" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableSenderEmail(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetSenderEmail(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *EmailProviderUpdate) SetSenderName(v string) *EmailProviderUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableSenderName(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailProviderUpdate) SetStatus(v string) *EmailProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableStatus(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *EmailProviderUpdate) SetLastCheckedAt(v time.Time) *EmailProviderUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableLastCheckedAt(v *time.Time) *EmailProviderUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *EmailProviderUpdate) ClearLastCheckedAt() *EmailProviderUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *EmailProviderUpdate) SetLastError(v string) *EmailProviderUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableLastError(v *string) *EmailProviderUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *EmailProviderUpdate) SetConsecutiveFailures(v int) *EmailProviderUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *EmailProviderUpdate) SetNillableConsecutiveFailures(v *int) *EmailProviderUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *EmailProviderUpdate) AddConsecutiveFailures(v int) *EmailProviderUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailProviderUpdate) SetUpdatedAt(v time.Time) *EmailProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailProviderMutation object of the builder.
func (_u *EmailProviderUpdate) Mutation() *EmailProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailProviderUpdate) check() error {
	if v, ok := _u.mutation.APIKey(); ok {
		if err := emailprovider.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderEmail(); ok {
		if err := emailprovider.SenderEmailValidator(v); err != nil {
			return &ValidationError{Name: "sender_email", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderName(); ok {
		if err := emailprovider.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_name": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailprovider.Table, emailprovider.Columns, sqlgraph.NewFieldSpec(emailprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(emailprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(emailprovider.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderEmail(); ok {
		_spec.SetField(emailprovider.FieldSenderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(emailprovider.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(emailprovider.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(emailprovider.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(emailprovider.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(emailprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(emailprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailProviderUpdateOne is the builder for updating a single EmailProvider entity.
type EmailProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailProviderMutation
}

// SetProvider sets the "provider" field.
func (_u *EmailProviderUpdateOne) SetProvider(v string) *EmailProviderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableProvider(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *EmailProviderUpdateOne) SetAPIKey(v string) *EmailProviderUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableAPIKey(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSenderEmail sets the "sender_email" field.
func (_u *EmailProviderUpdateOne) SetSenderEmail(v string) *EmailProviderUpdateOne {
	_u.mutation.SetSenderEmail(v)
	return _u
}

// SetNillableSenderEmail sets the "sender_email" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableSenderEmail(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetSenderEmail(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *EmailProviderUpdateOne) SetSenderName(v string) *EmailProviderUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableSenderName(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailProviderUpdateOne) SetStatus(v string) *EmailProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableStatus(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *EmailProviderUpdateOne) SetLastCheckedAt(v time.Time) *EmailProviderUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableLastCheckedAt(v *time.Time) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *EmailProviderUpdateOne) ClearLastCheckedAt() *EmailProviderUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *EmailProviderUpdateOne) SetLastError(v string) *EmailProviderUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableLastError(v *string) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *EmailProviderUpdateOne) SetConsecutiveFailures(v int) *EmailProviderUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *EmailProviderUpdateOne) SetNillableConsecutiveFailures(v *int) *EmailProviderUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *EmailProviderUpdateOne) AddConsecutiveFailures(v int) *EmailProviderUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailProviderUpdateOne) SetUpdatedAt(v time.Time) *EmailProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailProviderMutation object of the builder.
func (_u *EmailProviderUpdateOne) Mutation() *EmailProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailProviderUpdate builder.
func (_u *EmailProviderUpdateOne) Where(ps ...predicate.EmailProvider) *EmailProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailProviderUpdateOne) Select(field string, fields ...string) *EmailProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailProvider entity.
func (_u *EmailProviderUpdateOne) Save(ctx context.Context) (*EmailProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailProviderUpdateOne) SaveX(ctx context.Context) *EmailProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailProviderUpdateOne) check() error {
	if v, ok := _u.mutation.APIKey(); ok {
		if err := emailprovider.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderEmail(); ok {
		if err := emailprovider.SenderEmailValidator(v); err != nil {
			return &ValidationError{Name: "sender_email", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderName(); ok {
		if err := emailprovider.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_name": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailProviderUpdateOne) sqlSave(ctx context.Context) (_node *EmailProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailprovider.Table, emailprovider.Columns, sqlgraph.NewFieldSpec(emailprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailprovider.FieldID)
		for _, f := range fields {
			if !emailprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(emailprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(emailprovider.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderEmail(); ok {
		_spec.SetField(emailprovider.FieldSenderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(emailprovider.FieldSenderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(emailprovider.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(emailprovider.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(emailprovider.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(emailprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(emailprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EmailProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
