// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/emailprovider"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailProviderCreate is the builder for creating a EmailProvider entity.
type EmailProviderCreate struct {
	config
	mutation *EmailProviderMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *EmailProviderCreate) SetProvider(v string) *EmailProviderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableProvider(v *string) *EmailProviderCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *EmailProviderCreate) SetAPIKey(v string) *EmailProviderCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetSenderEmail sets the "sender_email" field.
func (_c *EmailProviderCreate) SetSenderEmail(v string) *EmailProviderCreate {
	_c.mutation.SetSenderEmail(v)
	return _c
}

// SetSenderName sets the "sender_name" field.
func (_c *EmailProviderCreate) SetSenderName(v string) *EmailProviderCreate {
	_c.mutation.SetSenderName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EmailProviderCreate) SetStatus(v string) *EmailProviderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableStatus(v *string) *EmailProviderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *EmailProviderCreate) SetLastCheckedAt(v time.Time) *EmailProviderCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableLastCheckedAt(v *time.Time) *EmailProviderCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *EmailProviderCreate) SetLastError(v string) *EmailProviderCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableLastError(v *string) *EmailProviderCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_c *EmailProviderCreate) SetConsecutiveFailures(v int) *EmailProviderCreate {
	_c.mutation.SetConsecutiveFailures(v)
	return _c
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableConsecutiveFailures(v *int) *EmailProviderCreate {
	if v != nil {
		_c.SetConsecutiveFailures(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailProviderCreate) SetCreatedAt(v time.Time) *EmailProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableCreatedAt(v *time.Time) *EmailProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailProviderCreate) SetUpdatedAt(v time.Time) *EmailProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailProviderCreate) SetNillableUpdatedAt(v *time.Time) *EmailProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailProviderCreate) SetID(v int64) *EmailProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EmailProviderMutation object of the builder.
func (_c *EmailProviderCreate) Mutation() *EmailProviderMutation {
	return _c.mutation
}

// Save creates the EmailProvider in the database.
func (_c *EmailProviderCreate) Save(ctx context.Context) (*EmailProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailProviderCreate) SaveX(ctx context.Context) *EmailProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailProviderCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := emailprovider.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := emailprovider.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := emailprovider.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		v := emailprovider.DefaultConsecutiveFailures
		_c.mutation.SetConsecutiveFailures(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emailprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailProviderCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "EmailProvider.provider"`)}
	}
	if _, ok := _c.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "EmailProvider.api_key"`)}
	}
	if v, ok := _c.mutation.APIKey(); ok {
		if err := emailprovider.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SenderEmail(); !ok {
		return &ValidationError{Name: "sender_email", err: errors.New(`ent: missing required field "EmailProvider.sender_email"`)}
	}
	if v, ok := _c.mutation.SenderEmail(); ok {
		if err := emailprovider.SenderEmailValidator(v); err != nil {
			return &ValidationError{Name: "sender_email", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SenderName(); !ok {
		return &ValidationError{Name: "sender_name", err: errors.New(`ent: missing required field "EmailProvider.sender_name"`)}
	}
	if v, ok := _c.mutation.SenderName(); ok {
		if err := emailprovider.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "EmailProvider.sender_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EmailProvider.status"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "EmailProvider.last_error"`)}
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		return &ValidationError{Name: "consecutive_failures", err: errors.New(`ent: missing required field "EmailProvider.consecutive_failures"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailProvider.updated_at"`)}
	}
	return nil
}

func (_c *EmailProviderCreate) sqlSave(ctx context.Context) (*EmailProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailProviderCreate) createSpec() (*EmailProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailprovider.Table, sqlgraph.NewFieldSpec(emailprovider.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(emailprovider.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(emailprovider.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.SenderEmail(); ok {
		_spec.SetField(emailprovider.FieldSenderEmail, field.TypeString, value)
		_node.SenderEmail = value
	}
	if value, ok := _c.mutation.SenderName(); ok {
		_spec.SetField(emailprovider.FieldSenderName, field.TypeString, value)
		_node.SenderName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(emailprovider.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(emailprovider.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(emailprovider.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(emailprovider.FieldConsecutiveFailures, field.TypeInt, value)
		_node.ConsecutiveFailures = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EmailProviderCreateBulk is the builder for creating many EmailProvider entities in bulk.
type EmailProviderCreateBulk struct {
	config
	err      error
	builders []*EmailProviderCreate
}

// Save creates the EmailProvider entities in the database.
func (_c *EmailProviderCreateBulk) Save(ctx context.Context) ([]*EmailProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailProviderCreateBulk) SaveX(ctx context.Context) []*EmailProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
