// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/invite"
	"taskai/ent/predicate"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InviteUpdate is the builder for updating Invite entities.
type InviteUpdate struct {
	config
	hooks    []Hook
	mutation *InviteMutation
}

// Where appends a list predicates to the InviteUpdate builder.
func (_u *InviteUpdate) Where(ps ...predicate.Invite) *InviteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *InviteUpdate) SetCode(v string) *InviteUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableCode(v *string) *InviteUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *InviteUpdate) SetInviterID(v int64) *InviteUpdate {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableInviterID(v *int64) *InviteUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InviteUpdate) SetInviteeID(v int64) *InviteUpdate {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableInviteeID(v *int64) *InviteUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (_u *InviteUpdate) ClearInviteeID() *InviteUpdate {
	_u.mutation.ClearInviteeID()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *InviteUpdate) SetUsedAt(v time.Time) *InviteUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableUsedAt(v *time.Time) *InviteUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *InviteUpdate) ClearUsedAt() *InviteUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteUpdate) SetExpiresAt(v time.Time) *InviteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableExpiresAt(v *time.Time) *InviteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InviteUpdate) ClearExpiresAt() *InviteUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteUpdate) SetInviter(v *User) *InviteUpdate {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteUpdate) SetInvitee(v *User) *InviteUpdate {
	return _u.SetInviteeID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_u *InviteUpdate) Mutation() *InviteMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteUpdate) ClearInviter() *InviteUpdate {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteUpdate) ClearInvitee() *InviteUpdate {
	_u.mutation.ClearInvitee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invite.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Invite.code": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.inviter"`)
	}
	return nil
}

func (_u *InviteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invite.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(invite.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(invite.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invite.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviterTable,
			Columns: []string{invite.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviterTable,
			Columns: []string{invite.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviteeTable,
			Columns: []string{invite.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviteeTable,
			Columns: []string{invite.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteUpdateOne is the builder for updating a single Invite entity.
type InviteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteMutation
}

// SetCode sets the "code" field.
func (_u *InviteUpdateOne) SetCode(v string) *InviteUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableCode(v *string) *InviteUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *InviteUpdateOne) SetInviterID(v int64) *InviteUpdateOne {
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableInviterID(v *int64) *InviteUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *InviteUpdateOne) SetInviteeID(v int64) *InviteUpdateOne {
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableInviteeID(v *int64) *InviteUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// ClearInviteeID clears the value of the "invitee_id" field.
func (_u *InviteUpdateOne) ClearInviteeID() *InviteUpdateOne {
	_u.mutation.ClearInviteeID()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *InviteUpdateOne) SetUsedAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableUsedAt(v *time.Time) *InviteUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *InviteUpdateOne) ClearUsedAt() *InviteUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InviteUpdateOne) SetExpiresAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableExpiresAt(v *time.Time) *InviteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InviteUpdateOne) ClearExpiresAt() *InviteUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteUpdateOne) SetInviter(v *User) *InviteUpdateOne {
	return _u.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteUpdateOne) SetInvitee(v *User) *InviteUpdateOne {
	return _u.SetInviteeID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_u *InviteUpdateOne) Mutation() *InviteMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteUpdateOne) ClearInviter() *InviteUpdateOne {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteUpdateOne) ClearInvitee() *InviteUpdateOne {
	_u.mutation.ClearInvitee()
	return _u
}

// Where appends a list predicates to the InviteUpdate builder.
func (_u *InviteUpdateOne) Where(ps ...predicate.Invite) *InviteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteUpdateOne) Select(field string, fields ...string) *InviteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invite entity.
func (_u *InviteUpdateOne) Save(ctx context.Context) (*Invite, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteUpdateOne) SaveX(ctx context.Context) *Invite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invite.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Invite.code": %w`, err)}
		}
	}
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.inviter"`)
	}
	return nil
}

func (_u *InviteUpdateOne) sqlSave(ctx context.Context) (_node *Invite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invite.FieldID)
		for _, f := range fields {
			if !invite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invite.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(invite.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(invite.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invite.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviterTable,
			Columns: []string{invite.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviterTable,
			Columns: []string{invite.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviteeTable,
			Columns: []string{invite.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InviteeTable,
			Columns: []string{invite.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
