// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/pageversion"
	"taskai/ent/predicate"
	"taskai/ent/wikipage"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PageVersionUpdate is the builder for updating PageVersion entities.
type PageVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PageVersionMutation
}

// Where appends a list predicates to the PageVersionUpdate builder.
func (_u *PageVersionUpdate) Where(ps ...predicate.PageVersion) *PageVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPageID sets the "page_id" field.
func (_u *PageVersionUpdate) SetPageID(v int64) *PageVersionUpdate {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *PageVersionUpdate) SetNillablePageID(v *int64) *PageVersionUpdate {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *PageVersionUpdate) SetVersionNumber(v int) *PageVersionUpdate {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *PageVersionUpdate) SetNillableVersionNumber(v *int) *PageVersionUpdate {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *PageVersionUpdate) AddVersionNumber(v int) *PageVersionUpdate {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetYjsState sets the "yjs_state" field.
func (_u *PageVersionUpdate) SetYjsState(v []byte) *PageVersionUpdate {
	_u.mutation.SetYjsState(v)
	return _u
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_u *PageVersionUpdate) SetPage(v *WikiPage) *PageVersionUpdate {
	return _u.SetPageID(v.ID)
}

// Mutation returns the PageVersionMutation object of the builder.
func (_u *PageVersionUpdate) Mutation() *PageVersionMutation {
	return _u.mutation
}

// ClearPage clears the "page" edge to the WikiPage entity.
func (_u *PageVersionUpdate) ClearPage() *PageVersionUpdate {
	_u.mutation.ClearPage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PageVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PageVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageVersionUpdate) check() error {
	if v, ok := _u.mutation.YjsState(); ok {
		if err := pageversion.YjsStateValidator(v); err != nil {
			return &ValidationError{Name: "yjs_state", err: fmt.Errorf(`ent: validator failed for field "PageVersion.yjs_state": %w`, err)}
		}
	}
	if _u.mutation.PageCleared() && len(_u.mutation.PageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PageVersion.page"`)
	}
	return nil
}

func (_u *PageVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pageversion.Table, pageversion.Columns, sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(pageversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(pageversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YjsState(); ok {
		_spec.SetField(pageversion.FieldYjsState, field.TypeBytes, value)
	}
	if _u.mutation.PageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pageversion.PageTable,
			Columns: []string{pageversion.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pageversion.PageTable,
			Columns: []string{pageversion.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PageVersionUpdateOne is the builder for updating a single PageVersion entity.
type PageVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PageVersionMutation
}

// SetPageID sets the "page_id" field.
func (_u *PageVersionUpdateOne) SetPageID(v int64) *PageVersionUpdateOne {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *PageVersionUpdateOne) SetNillablePageID(v *int64) *PageVersionUpdateOne {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetVersionNumber sets the "version_number" field.
func (_u *PageVersionUpdateOne) SetVersionNumber(v int) *PageVersionUpdateOne {
	_u.mutation.ResetVersionNumber()
	_u.mutation.SetVersionNumber(v)
	return _u
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_u *PageVersionUpdateOne) SetNillableVersionNumber(v *int) *PageVersionUpdateOne {
	if v != nil {
		_u.SetVersionNumber(*v)
	}
	return _u
}

// AddVersionNumber adds value to the "version_number" field.
func (_u *PageVersionUpdateOne) AddVersionNumber(v int) *PageVersionUpdateOne {
	_u.mutation.AddVersionNumber(v)
	return _u
}

// SetYjsState sets the "yjs_state" field.
func (_u *PageVersionUpdateOne) SetYjsState(v []byte) *PageVersionUpdateOne {
	_u.mutation.SetYjsState(v)
	return _u
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_u *PageVersionUpdateOne) SetPage(v *WikiPage) *PageVersionUpdateOne {
	return _u.SetPageID(v.ID)
}

// Mutation returns the PageVersionMutation object of the builder.
func (_u *PageVersionUpdateOne) Mutation() *PageVersionMutation {
	return _u.mutation
}

// ClearPage clears the "page" edge to the WikiPage entity.
func (_u *PageVersionUpdateOne) ClearPage() *PageVersionUpdateOne {
	_u.mutation.ClearPage()
	return _u
}

// Where appends a list predicates to the PageVersionUpdate builder.
func (_u *PageVersionUpdateOne) Where(ps ...predicate.PageVersion) *PageVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PageVersionUpdateOne) Select(field string, fields ...string) *PageVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PageVersion entity.
func (_u *PageVersionUpdateOne) Save(ctx context.Context) (*PageVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageVersionUpdateOne) SaveX(ctx context.Context) *PageVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PageVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageVersionUpdateOne) check() error {
	if v, ok := _u.mutation.YjsState(); ok {
		if err := pageversion.YjsStateValidator(v); err != nil {
			return &ValidationError{Name: "yjs_state", err: fmt.Errorf(`ent: validator failed for field "PageVersion.yjs_state": %w`, err)}
		}
	}
	if _u.mutation.PageCleared() && len(_u.mutation.PageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PageVersion.page"`)
	}
	return nil
}

func (_u *PageVersionUpdateOne) sqlSave(ctx context.Context) (_node *PageVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pageversion.Table, pageversion.Columns, sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PageVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pageversion.FieldID)
		for _, f := range fields {
			if !pageversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pageversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VersionNumber(); ok {
		_spec.SetField(pageversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNumber(); ok {
		_spec.AddField(pageversion.FieldVersionNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.YjsState(); ok {
		_spec.SetField(pageversion.FieldYjsState, field.TypeBytes, value)
	}
	if _u.mutation.PageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pageversion.PageTable,
			Columns: []string{pageversion.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pageversion.PageTable,
			Columns: []string{pageversion.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PageVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
