// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/pageversion"
	"taskai/ent/wikipage"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PageVersionCreate is the builder for creating a PageVersion entity.
type PageVersionCreate struct {
	config
	mutation *PageVersionMutation
	hooks    []Hook
}

// SetPageID sets the "page_id" field.
func (_c *PageVersionCreate) SetPageID(v int64) *PageVersionCreate {
	_c.mutation.SetPageID(v)
	return _c
}

// SetVersionNumber sets the "version_number" field.
func (_c *PageVersionCreate) SetVersionNumber(v int) *PageVersionCreate {
	_c.mutation.SetVersionNumber(v)
	return _c
}

// SetYjsState sets the "yjs_state" field.
func (_c *PageVersionCreate) SetYjsState(v []byte) *PageVersionCreate {
	_c.mutation.SetYjsState(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PageVersionCreate) SetCreatedAt(v time.Time) *PageVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PageVersionCreate) SetNillableCreatedAt(v *time.Time) *PageVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PageVersionCreate) SetID(v int64) *PageVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_c *PageVersionCreate) SetPage(v *WikiPage) *PageVersionCreate {
	return _c.SetPageID(v.ID)
}

// Mutation returns the PageVersionMutation object of the builder.
func (_c *PageVersionCreate) Mutation() *PageVersionMutation {
	return _c.mutation
}

// Save creates the PageVersion in the database.
func (_c *PageVersionCreate) Save(ctx context.Context) (*PageVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PageVersionCreate) SaveX(ctx context.Context) *PageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PageVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pageversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PageVersionCreate) check() error {
	if _, ok := _c.mutation.PageID(); !ok {
		return &ValidationError{Name: "page_id", err: errors.New(`ent: missing required field "PageVersion.page_id"`)}
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		return &ValidationError{Name: "version_number", err: errors.New(`ent: missing required field "PageVersion.version_number"`)}
	}
	if _, ok := _c.mutation.YjsState(); !ok {
		return &ValidationError{Name: "yjs_state", err: errors.New(`ent: missing required field "PageVersion.yjs_state"`)}
	}
	if v, ok := _c.mutation.YjsState(); ok {
		if err := pageversion.YjsStateValidator(v); err != nil {
			return &ValidationError{Name: "yjs_state", err: fmt.Errorf(`ent: validator failed for field "PageVersion.yjs_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PageVersion.created_at"`)}
	}
	if len(_c.mutation.PageIDs()) == 0 {
		return &ValidationError{Name: "page", err: errors.New(`ent: missing required edge "PageVersion.page"`)}
	}
	return nil
}

func (_c *PageVersionCreate) sqlSave(ctx context.Context) (*PageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PageVersionCreate) createSpec() (*PageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pageversion.Table, sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.VersionNumber(); ok {
		_spec.SetField(pageversion.FieldVersionNumber, field.TypeInt, value)
		_node.VersionNumber = value
	}
	if value, ok := _c.mutation.YjsState(); ok {
		_spec.SetField(pageversion.FieldYjsState, field.TypeBytes, value)
		_node.YjsState = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pageversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pageversion.PageTable,
			Columns: []string{pageversion.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PageVersionCreateBulk is the builder for creating many PageVersion entities in bulk.
type PageVersionCreateBulk struct {
	config
	err      error
	builders []*PageVersionCreate
}

// Save creates the PageVersion entities in the database.
func (_c *PageVersionCreateBulk) Save(ctx context.Context) ([]*PageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PageVersionCreateBulk) SaveX(ctx context.Context) []*PageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
