// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/predicate"
	"taskai/ent/sprint"
	"taskai/ent/task"
	"taskai/ent/team"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SprintUpdate is the builder for updating Sprint entities.
type SprintUpdate struct {
	config
	hooks    []Hook
	mutation *SprintMutation
}

// Where appends a list predicates to the SprintUpdate builder.
func (_u *SprintUpdate) Where(ps ...predicate.Sprint) *SprintUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SprintUpdate) SetUserID(v int64) *SprintUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableUserID(v *int64) *SprintUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *SprintUpdate) SetTeamID(v int64) *SprintUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableTeamID(v *int64) *SprintUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *SprintUpdate) ClearTeamID() *SprintUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetName sets the "name" field.
func (_u *SprintUpdate) SetName(v string) *SprintUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableName(v *string) *SprintUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGoal sets the "goal" field.
func (_u *SprintUpdate) SetGoal(v string) *SprintUpdate {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableGoal(v *string) *SprintUpdate {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// ClearGoal clears the value of the "goal" field.
func (_u *SprintUpdate) ClearGoal() *SprintUpdate {
	_u.mutation.ClearGoal()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *SprintUpdate) SetStartDate(v time.Time) *SprintUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableStartDate(v *time.Time) *SprintUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *SprintUpdate) ClearStartDate() *SprintUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *SprintUpdate) SetEndDate(v time.Time) *SprintUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableEndDate(v *time.Time) *SprintUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *SprintUpdate) ClearEndDate() *SprintUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SprintUpdate) SetStatus(v string) *SprintUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SprintUpdate) SetNillableStatus(v *string) *SprintUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SprintUpdate) SetUpdatedAt(v time.Time) *SprintUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SprintUpdate) SetUser(v *User) *SprintUpdate {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SprintUpdate) SetTeam(v *Team) *SprintUpdate {
	return _u.SetTeamID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SprintUpdate) AddTaskIDs(ids ...int64) *SprintUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SprintUpdate) AddTasks(v ...*Task) *SprintUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the SprintMutation object of the builder.
func (_u *SprintUpdate) Mutation() *SprintMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SprintUpdate) ClearUser() *SprintUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SprintUpdate) ClearTeam() *SprintUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SprintUpdate) ClearTasks() *SprintUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SprintUpdate) RemoveTaskIDs(ids ...int64) *SprintUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SprintUpdate) RemoveTasks(v ...*Task) *SprintUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SprintUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SprintUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SprintUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SprintUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SprintUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sprint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SprintUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sprint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sprint.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sprint.user"`)
	}
	return nil
}

func (_u *SprintUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sprint.Table, sprint.Columns, sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sprint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(sprint.FieldGoal, field.TypeString, value)
	}
	if _u.mutation.GoalCleared() {
		_spec.ClearField(sprint.FieldGoal, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(sprint.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(sprint.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(sprint.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(sprint.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sprint.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sprint.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.UserTable,
			Columns: []string{sprint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.UserTable,
			Columns: []string{sprint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.TeamTable,
			Columns: []string{sprint.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.TeamTable,
			Columns: []string{sprint.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sprint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SprintUpdateOne is the builder for updating a single Sprint entity.
type SprintUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SprintMutation
}

// SetUserID sets the "user_id" field.
func (_u *SprintUpdateOne) SetUserID(v int64) *SprintUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableUserID(v *int64) *SprintUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *SprintUpdateOne) SetTeamID(v int64) *SprintUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableTeamID(v *int64) *SprintUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *SprintUpdateOne) ClearTeamID() *SprintUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetName sets the "name" field.
func (_u *SprintUpdateOne) SetName(v string) *SprintUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableName(v *string) *SprintUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGoal sets the "goal" field.
func (_u *SprintUpdateOne) SetGoal(v string) *SprintUpdateOne {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableGoal(v *string) *SprintUpdateOne {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// ClearGoal clears the value of the "goal" field.
func (_u *SprintUpdateOne) ClearGoal() *SprintUpdateOne {
	_u.mutation.ClearGoal()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *SprintUpdateOne) SetStartDate(v time.Time) *SprintUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableStartDate(v *time.Time) *SprintUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *SprintUpdateOne) ClearStartDate() *SprintUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *SprintUpdateOne) SetEndDate(v time.Time) *SprintUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableEndDate(v *time.Time) *SprintUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *SprintUpdateOne) ClearEndDate() *SprintUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SprintUpdateOne) SetStatus(v string) *SprintUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SprintUpdateOne) SetNillableStatus(v *string) *SprintUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SprintUpdateOne) SetUpdatedAt(v time.Time) *SprintUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SprintUpdateOne) SetUser(v *User) *SprintUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SprintUpdateOne) SetTeam(v *Team) *SprintUpdateOne {
	return _u.SetTeamID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SprintUpdateOne) AddTaskIDs(ids ...int64) *SprintUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SprintUpdateOne) AddTasks(v ...*Task) *SprintUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the SprintMutation object of the builder.
func (_u *SprintUpdateOne) Mutation() *SprintMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SprintUpdateOne) ClearUser() *SprintUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SprintUpdateOne) ClearTeam() *SprintUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SprintUpdateOne) ClearTasks() *SprintUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SprintUpdateOne) RemoveTaskIDs(ids ...int64) *SprintUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SprintUpdateOne) RemoveTasks(v ...*Task) *SprintUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the SprintUpdate builder.
func (_u *SprintUpdateOne) Where(ps ...predicate.Sprint) *SprintUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SprintUpdateOne) Select(field string, fields ...string) *SprintUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sprint entity.
func (_u *SprintUpdateOne) Save(ctx context.Context) (*Sprint, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SprintUpdateOne) SaveX(ctx context.Context) *Sprint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SprintUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SprintUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SprintUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sprint.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SprintUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sprint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sprint.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sprint.user"`)
	}
	return nil
}

func (_u *SprintUpdateOne) sqlSave(ctx context.Context) (_node *Sprint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sprint.Table, sprint.Columns, sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sprint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sprint.FieldID)
		for _, f := range fields {
			if !sprint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sprint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sprint.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(sprint.FieldGoal, field.TypeString, value)
	}
	if _u.mutation.GoalCleared() {
		_spec.ClearField(sprint.FieldGoal, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(sprint.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(sprint.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(sprint.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(sprint.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sprint.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sprint.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.UserTable,
			Columns: []string{sprint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.UserTable,
			Columns: []string{sprint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.TeamTable,
			Columns: []string{sprint.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.TeamTable,
			Columns: []string{sprint.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sprint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sprint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
