// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/sprint"
	"taskai/ent/task"
	"taskai/ent/team"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SprintCreate is the builder for creating a Sprint entity.
type SprintCreate struct {
	config
	mutation *SprintMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SprintCreate) SetUserID(v int64) *SprintCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *SprintCreate) SetTeamID(v int64) *SprintCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_c *SprintCreate) SetNillableTeamID(v *int64) *SprintCreate {
	if v != nil {
		_c.SetTeamID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SprintCreate) SetName(v string) *SprintCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGoal sets the "goal" field.
func (_c *SprintCreate) SetGoal(v string) *SprintCreate {
	_c.mutation.SetGoal(v)
	return _c
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_c *SprintCreate) SetNillableGoal(v *string) *SprintCreate {
	if v != nil {
		_c.SetGoal(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *SprintCreate) SetStartDate(v time.Time) *SprintCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *SprintCreate) SetNillableStartDate(v *time.Time) *SprintCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *SprintCreate) SetEndDate(v time.Time) *SprintCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *SprintCreate) SetNillableEndDate(v *time.Time) *SprintCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SprintCreate) SetStatus(v string) *SprintCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SprintCreate) SetNillableStatus(v *string) *SprintCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SprintCreate) SetCreatedAt(v time.Time) *SprintCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SprintCreate) SetNillableCreatedAt(v *time.Time) *SprintCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SprintCreate) SetUpdatedAt(v time.Time) *SprintCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SprintCreate) SetNillableUpdatedAt(v *time.Time) *SprintCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SprintCreate) SetID(v int64) *SprintCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SprintCreate) SetUser(v *User) *SprintCreate {
	return _c.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *SprintCreate) SetTeam(v *Team) *SprintCreate {
	return _c.SetTeamID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *SprintCreate) AddTaskIDs(ids ...int64) *SprintCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *SprintCreate) AddTasks(v ...*Task) *SprintCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the SprintMutation object of the builder.
func (_c *SprintCreate) Mutation() *SprintMutation {
	return _c.mutation
}

// Save creates the Sprint in the database.
func (_c *SprintCreate) Save(ctx context.Context) (*Sprint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SprintCreate) SaveX(ctx context.Context) *Sprint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SprintCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SprintCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SprintCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := sprint.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sprint.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sprint.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SprintCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Sprint.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Sprint.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sprint.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sprint.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Sprint.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sprint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sprint.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Sprint.user"`)}
	}
	return nil
}

func (_c *SprintCreate) sqlSave(ctx context.Context) (*Sprint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SprintCreate) createSpec() (*Sprint, *sqlgraph.CreateSpec) {
	var (
		_node = &Sprint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sprint.Table, sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sprint.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Goal(); ok {
		_spec.SetField(sprint.FieldGoal, field.TypeString, value)
		_node.Goal = &value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(sprint.FieldStartDate, field.TypeTime, value)
		_node.StartDate = &value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(sprint.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sprint.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sprint.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sprint.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.UserTable,
			Columns: []string{sprint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sprint.TeamTable,
			Columns: []string{sprint.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sprint.TasksTable,
			Columns: []string{sprint.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SprintCreateBulk is the builder for creating many Sprint entities in bulk.
type SprintCreateBulk struct {
	config
	err      error
	builders []*SprintCreate
}

// Save creates the Sprint entities in the database.
func (_c *SprintCreateBulk) Save(ctx context.Context) ([]*Sprint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sprint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SprintMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SprintCreateBulk) SaveX(ctx context.Context) []*Sprint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SprintCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SprintCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
