// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/predicate"
	"taskai/ent/project"
	"taskai/ent/swimlane"
	"taskai/ent/task"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SwimLaneUpdate is the builder for updating SwimLane entities.
type SwimLaneUpdate struct {
	config
	hooks    []Hook
	mutation *SwimLaneMutation
}

// Where appends a list predicates to the SwimLaneUpdate builder.
func (_u *SwimLaneUpdate) Where(ps ...predicate.SwimLane) *SwimLaneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *SwimLaneUpdate) SetProjectID(v int64) *SwimLaneUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SwimLaneUpdate) SetNillableProjectID(v *int64) *SwimLaneUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SwimLaneUpdate) SetName(v string) *SwimLaneUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SwimLaneUpdate) SetNillableName(v *string) *SwimLaneUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SwimLaneUpdate) SetColor(v string) *SwimLaneUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SwimLaneUpdate) SetNillableColor(v *string) *SwimLaneUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *SwimLaneUpdate) SetPosition(v int) *SwimLaneUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *SwimLaneUpdate) SetNillablePosition(v *int) *SwimLaneUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *SwimLaneUpdate) AddPosition(v int) *SwimLaneUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetStatusCategory sets the "status_category" field.
func (_u *SwimLaneUpdate) SetStatusCategory(v string) *SwimLaneUpdate {
	_u.mutation.SetStatusCategory(v)
	return _u
}

// SetNillableStatusCategory sets the "status_category" field if the given value is not nil.
func (_u *SwimLaneUpdate) SetNillableStatusCategory(v *string) *SwimLaneUpdate {
	if v != nil {
		_u.SetStatusCategory(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SwimLaneUpdate) SetUpdatedAt(v time.Time) *SwimLaneUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SwimLaneUpdate) SetProject(v *Project) *SwimLaneUpdate {
	return _u.SetProjectID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SwimLaneUpdate) AddTaskIDs(ids ...int64) *SwimLaneUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SwimLaneUpdate) AddTasks(v ...*Task) *SwimLaneUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the SwimLaneMutation object of the builder.
func (_u *SwimLaneUpdate) Mutation() *SwimLaneMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SwimLaneUpdate) ClearProject() *SwimLaneUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SwimLaneUpdate) ClearTasks() *SwimLaneUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SwimLaneUpdate) RemoveTaskIDs(ids ...int64) *SwimLaneUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SwimLaneUpdate) RemoveTasks(v ...*Task) *SwimLaneUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SwimLaneUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SwimLaneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SwimLaneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SwimLaneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SwimLaneUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := swimlane.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SwimLaneUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := swimlane.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SwimLane.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := swimlane.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "SwimLane.color": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SwimLane.project"`)
	}
	return nil
}

func (_u *SwimLaneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(swimlane.Table, swimlane.Columns, sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(swimlane.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(swimlane.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(swimlane.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(swimlane.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusCategory(); ok {
		_spec.SetField(swimlane.FieldStatusCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(swimlane.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   swimlane.ProjectTable,
			Columns: []string{swimlane.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   swimlane.ProjectTable,
			Columns: []string{swimlane.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{swimlane.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SwimLaneUpdateOne is the builder for updating a single SwimLane entity.
type SwimLaneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SwimLaneMutation
}

// SetProjectID sets the "project_id" field.
func (_u *SwimLaneUpdateOne) SetProjectID(v int64) *SwimLaneUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SwimLaneUpdateOne) SetNillableProjectID(v *int64) *SwimLaneUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SwimLaneUpdateOne) SetName(v string) *SwimLaneUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SwimLaneUpdateOne) SetNillableName(v *string) *SwimLaneUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SwimLaneUpdateOne) SetColor(v string) *SwimLaneUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SwimLaneUpdateOne) SetNillableColor(v *string) *SwimLaneUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *SwimLaneUpdateOne) SetPosition(v int) *SwimLaneUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *SwimLaneUpdateOne) SetNillablePosition(v *int) *SwimLaneUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *SwimLaneUpdateOne) AddPosition(v int) *SwimLaneUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetStatusCategory sets the "status_category" field.
func (_u *SwimLaneUpdateOne) SetStatusCategory(v string) *SwimLaneUpdateOne {
	_u.mutation.SetStatusCategory(v)
	return _u
}

// SetNillableStatusCategory sets the "status_category" field if the given value is not nil.
func (_u *SwimLaneUpdateOne) SetNillableStatusCategory(v *string) *SwimLaneUpdateOne {
	if v != nil {
		_u.SetStatusCategory(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SwimLaneUpdateOne) SetUpdatedAt(v time.Time) *SwimLaneUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SwimLaneUpdateOne) SetProject(v *Project) *SwimLaneUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SwimLaneUpdateOne) AddTaskIDs(ids ...int64) *SwimLaneUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SwimLaneUpdateOne) AddTasks(v ...*Task) *SwimLaneUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the SwimLaneMutation object of the builder.
func (_u *SwimLaneUpdateOne) Mutation() *SwimLaneMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SwimLaneUpdateOne) ClearProject() *SwimLaneUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SwimLaneUpdateOne) ClearTasks() *SwimLaneUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SwimLaneUpdateOne) RemoveTaskIDs(ids ...int64) *SwimLaneUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SwimLaneUpdateOne) RemoveTasks(v ...*Task) *SwimLaneUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the SwimLaneUpdate builder.
func (_u *SwimLaneUpdateOne) Where(ps ...predicate.SwimLane) *SwimLaneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SwimLaneUpdateOne) Select(field string, fields ...string) *SwimLaneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SwimLane entity.
func (_u *SwimLaneUpdateOne) Save(ctx context.Context) (*SwimLane, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SwimLaneUpdateOne) SaveX(ctx context.Context) *SwimLane {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SwimLaneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SwimLaneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SwimLaneUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := swimlane.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SwimLaneUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := swimlane.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SwimLane.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := swimlane.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "SwimLane.color": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SwimLane.project"`)
	}
	return nil
}

func (_u *SwimLaneUpdateOne) sqlSave(ctx context.Context) (_node *SwimLane, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(swimlane.Table, swimlane.Columns, sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SwimLane.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, swimlane.FieldID)
		for _, f := range fields {
			if !swimlane.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != swimlane.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(swimlane.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(swimlane.FieldColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(swimlane.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(swimlane.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusCategory(); ok {
		_spec.SetField(swimlane.FieldStatusCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(swimlane.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   swimlane.ProjectTable,
			Columns: []string{swimlane.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   swimlane.ProjectTable,
			Columns: []string{swimlane.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SwimLane{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{swimlane.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
