// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/project"
	"taskai/ent/swimlane"
	"taskai/ent/task"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SwimLaneCreate is the builder for creating a SwimLane entity.
type SwimLaneCreate struct {
	config
	mutation *SwimLaneMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *SwimLaneCreate) SetProjectID(v int64) *SwimLaneCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SwimLaneCreate) SetName(v string) *SwimLaneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *SwimLaneCreate) SetColor(v string) *SwimLaneCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *SwimLaneCreate) SetPosition(v int) *SwimLaneCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetStatusCategory sets the "status_category" field.
func (_c *SwimLaneCreate) SetStatusCategory(v string) *SwimLaneCreate {
	_c.mutation.SetStatusCategory(v)
	return _c
}

// SetNillableStatusCategory sets the "status_category" field if the given value is not nil.
func (_c *SwimLaneCreate) SetNillableStatusCategory(v *string) *SwimLaneCreate {
	if v != nil {
		_c.SetStatusCategory(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SwimLaneCreate) SetCreatedAt(v time.Time) *SwimLaneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SwimLaneCreate) SetNillableCreatedAt(v *time.Time) *SwimLaneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SwimLaneCreate) SetUpdatedAt(v time.Time) *SwimLaneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SwimLaneCreate) SetNillableUpdatedAt(v *time.Time) *SwimLaneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SwimLaneCreate) SetID(v int64) *SwimLaneCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *SwimLaneCreate) SetProject(v *Project) *SwimLaneCreate {
	return _c.SetProjectID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *SwimLaneCreate) AddTaskIDs(ids ...int64) *SwimLaneCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *SwimLaneCreate) AddTasks(v ...*Task) *SwimLaneCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the SwimLaneMutation object of the builder.
func (_c *SwimLaneCreate) Mutation() *SwimLaneMutation {
	return _c.mutation
}

// Save creates the SwimLane in the database.
func (_c *SwimLaneCreate) Save(ctx context.Context) (*SwimLane, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SwimLaneCreate) SaveX(ctx context.Context) *SwimLane {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SwimLaneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SwimLaneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SwimLaneCreate) defaults() {
	if _, ok := _c.mutation.StatusCategory(); !ok {
		v := swimlane.DefaultStatusCategory
		_c.mutation.SetStatusCategory(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := swimlane.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := swimlane.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SwimLaneCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "SwimLane.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SwimLane.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := swimlane.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SwimLane.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "SwimLane.color"`)}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := swimlane.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "SwimLane.color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "SwimLane.position"`)}
	}
	if _, ok := _c.mutation.StatusCategory(); !ok {
		return &ValidationError{Name: "status_category", err: errors.New(`ent: missing required field "SwimLane.status_category"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SwimLane.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SwimLane.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "SwimLane.project"`)}
	}
	return nil
}

func (_c *SwimLaneCreate) sqlSave(ctx context.Context) (*SwimLane, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SwimLaneCreate) createSpec() (*SwimLane, *sqlgraph.CreateSpec) {
	var (
		_node = &SwimLane{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(swimlane.Table, sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(swimlane.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(swimlane.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(swimlane.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.StatusCategory(); ok {
		_spec.SetField(swimlane.FieldStatusCategory, field.TypeString, value)
		_node.StatusCategory = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(swimlane.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(swimlane.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   swimlane.ProjectTable,
			Columns: []string{swimlane.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   swimlane.TasksTable,
			Columns: []string{swimlane.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SwimLaneCreateBulk is the builder for creating many SwimLane entities in bulk.
type SwimLaneCreateBulk struct {
	config
	err      error
	builders []*SwimLaneCreate
}

// Save creates the SwimLane entities in the database.
func (_c *SwimLaneCreateBulk) Save(ctx context.Context) ([]*SwimLane, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SwimLane, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SwimLaneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SwimLaneCreateBulk) SaveX(ctx context.Context) []*SwimLane {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SwimLaneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SwimLaneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
