// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/predicate"
	"taskai/ent/task"
	"taskai/ent/taskcomment"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCommentUpdate is the builder for updating TaskComment entities.
type TaskCommentUpdate struct {
	config
	hooks    []Hook
	mutation *TaskCommentMutation
}

// Where appends a list predicates to the TaskCommentUpdate builder.
func (_u *TaskCommentUpdate) Where(ps ...predicate.TaskComment) *TaskCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskCommentUpdate) SetTaskID(v int64) *TaskCommentUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskCommentUpdate) SetNillableTaskID(v *int64) *TaskCommentUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskCommentUpdate) SetUserID(v int64) *TaskCommentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskCommentUpdate) SetNillableUserID(v *int64) *TaskCommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *TaskCommentUpdate) SetComment(v string) *TaskCommentUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *TaskCommentUpdate) SetNillableComment(v *string) *TaskCommentUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskCommentUpdate) SetUpdatedAt(v time.Time) *TaskCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskCommentUpdate) SetTask(v *Task) *TaskCommentUpdate {
	return _u.SetTaskID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskCommentUpdate) SetUser(v *User) *TaskCommentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TaskCommentMutation object of the builder.
func (_u *TaskCommentUpdate) Mutation() *TaskCommentMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskCommentUpdate) ClearTask() *TaskCommentUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskCommentUpdate) ClearUser() *TaskCommentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskCommentUpdate) check() error {
	if v, ok := _u.mutation.Comment(); ok {
		if err := taskcomment.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf(`ent: validator failed for field "TaskComment.comment": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskComment.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskComment.user"`)
	}
	return nil
}

func (_u *TaskCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskcomment.Table, taskcomment.Columns, sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(taskcomment.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.TaskTable,
			Columns: []string{taskcomment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.TaskTable,
			Columns: []string{taskcomment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.UserTable,
			Columns: []string{taskcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.UserTable,
			Columns: []string{taskcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskCommentUpdateOne is the builder for updating a single TaskComment entity.
type TaskCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskCommentMutation
}

// SetTaskID sets the "task_id" field.
func (_u *TaskCommentUpdateOne) SetTaskID(v int64) *TaskCommentUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskCommentUpdateOne) SetNillableTaskID(v *int64) *TaskCommentUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskCommentUpdateOne) SetUserID(v int64) *TaskCommentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskCommentUpdateOne) SetNillableUserID(v *int64) *TaskCommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *TaskCommentUpdateOne) SetComment(v string) *TaskCommentUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *TaskCommentUpdateOne) SetNillableComment(v *string) *TaskCommentUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskCommentUpdateOne) SetUpdatedAt(v time.Time) *TaskCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskCommentUpdateOne) SetTask(v *Task) *TaskCommentUpdateOne {
	return _u.SetTaskID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskCommentUpdateOne) SetUser(v *User) *TaskCommentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TaskCommentMutation object of the builder.
func (_u *TaskCommentUpdateOne) Mutation() *TaskCommentMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskCommentUpdateOne) ClearTask() *TaskCommentUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskCommentUpdateOne) ClearUser() *TaskCommentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TaskCommentUpdate builder.
func (_u *TaskCommentUpdateOne) Where(ps ...predicate.TaskComment) *TaskCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskCommentUpdateOne) Select(field string, fields ...string) *TaskCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskComment entity.
func (_u *TaskCommentUpdateOne) Save(ctx context.Context) (*TaskComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskCommentUpdateOne) SaveX(ctx context.Context) *TaskComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskCommentUpdateOne) check() error {
	if v, ok := _u.mutation.Comment(); ok {
		if err := taskcomment.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf(`ent: validator failed for field "TaskComment.comment": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskComment.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskComment.user"`)
	}
	return nil
}

func (_u *TaskCommentUpdateOne) sqlSave(ctx context.Context) (_node *TaskComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskcomment.Table, taskcomment.Columns, sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskcomment.FieldID)
		for _, f := range fields {
			if !taskcomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(taskcomment.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.TaskTable,
			Columns: []string{taskcomment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.TaskTable,
			Columns: []string{taskcomment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.UserTable,
			Columns: []string{taskcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskcomment.UserTable,
			Columns: []string{taskcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
