// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"taskai/ent/predicate"
	"taskai/ent/taskcomment"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCommentDelete is the builder for deleting a TaskComment entity.
type TaskCommentDelete struct {
	config
	hooks    []Hook
	mutation *TaskCommentMutation
}

// Where appends a list predicates to the TaskCommentDelete builder.
func (_d *TaskCommentDelete) Where(ps ...predicate.TaskComment) *TaskCommentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskCommentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCommentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskCommentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskcomment.Table, sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskCommentDeleteOne is the builder for deleting a single TaskComment entity.
type TaskCommentDeleteOne struct {
	_d *TaskCommentDelete
}

// Where appends a list predicates to the TaskCommentDelete builder.
func (_d *TaskCommentDeleteOne) Where(ps ...predicate.TaskComment) *TaskCommentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskCommentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskcomment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCommentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
