// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskai/ent/team"
	"taskai/ent/teaminvitation"
	"taskai/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TeamInvitation is the model entity for the TeamInvitation schema.
type TeamInvitation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID int64 `json:"inviter_id,omitempty"`
	// InviteeEmail holds the value of the "invitee_email" field.
	InviteeEmail string `json:"invitee_email,omitempty"`
	// InviteeID holds the value of the "invitee_id" field.
	InviteeID *int64 `json:"invitee_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AcceptanceToken holds the value of the "acceptance_token" field.
	AcceptanceToken *string `json:"acceptance_token,omitempty"`
	// InviteCode holds the value of the "invite_code" field.
	InviteCode *string `json:"invite_code,omitempty"`
	// TokenExpiresAt holds the value of the "token_expires_at" field.
	TokenExpiresAt *time.Time `json:"token_expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RespondedAt holds the value of the "responded_at" field.
	RespondedAt *time.Time `json:"responded_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamInvitationQuery when eager-loading is set.
	Edges        TeamInvitationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamInvitationEdges holds the relations/edges for other nodes in the graph.
type TeamInvitationEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// Inviter holds the value of the inviter edge.
	Inviter *User `json:"inviter,omitempty"`
	// Invitee holds the value of the invitee edge.
	Invitee *User `json:"invitee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamInvitationEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// InviterOrErr returns the Inviter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamInvitationEdges) InviterOrErr() (*User, error) {
	if e.Inviter != nil {
		return e.Inviter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "inviter"}
}

// InviteeOrErr returns the Invitee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamInvitationEdges) InviteeOrErr() (*User, error) {
	if e.Invitee != nil {
		return e.Invitee, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invitee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamInvitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teaminvitation.FieldID, teaminvitation.FieldTeamID, teaminvitation.FieldInviterID, teaminvitation.FieldInviteeID:
			values[i] = new(sql.NullInt64)
		case teaminvitation.FieldInviteeEmail, teaminvitation.FieldStatus, teaminvitation.FieldAcceptanceToken, teaminvitation.FieldInviteCode:
			values[i] = new(sql.NullString)
		case teaminvitation.FieldTokenExpiresAt, teaminvitation.FieldCreatedAt, teaminvitation.FieldRespondedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamInvitation fields.
func (_m *TeamInvitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teaminvitation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teaminvitation.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.Int64
			}
		case teaminvitation.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = value.Int64
			}
		case teaminvitation.FieldInviteeEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_email", values[i])
			} else if value.Valid {
				_m.InviteeEmail = value.String
			}
		case teaminvitation.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				_m.InviteeID = new(int64)
				*_m.InviteeID = value.Int64
			}
		case teaminvitation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case teaminvitation.FieldAcceptanceToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acceptance_token", values[i])
			} else if value.Valid {
				_m.AcceptanceToken = new(string)
				*_m.AcceptanceToken = value.String
			}
		case teaminvitation.FieldInviteCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invite_code", values[i])
			} else if value.Valid {
				_m.InviteCode = new(string)
				*_m.InviteCode = value.String
			}
		case teaminvitation.FieldTokenExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_expires_at", values[i])
			} else if value.Valid {
				_m.TokenExpiresAt = new(time.Time)
				*_m.TokenExpiresAt = value.Time
			}
		case teaminvitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case teaminvitation.FieldRespondedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field responded_at", values[i])
			} else if value.Valid {
				_m.RespondedAt = new(time.Time)
				*_m.RespondedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamInvitation.
// This includes values selected through modifiers, order, etc.
func (_m *TeamInvitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamInvitation entity.
func (_m *TeamInvitation) QueryTeam() *TeamQuery {
	return NewTeamInvitationClient(_m.config).QueryTeam(_m)
}

// QueryInviter queries the "inviter" edge of the TeamInvitation entity.
func (_m *TeamInvitation) QueryInviter() *UserQuery {
	return NewTeamInvitationClient(_m.config).QueryInviter(_m)
}

// QueryInvitee queries the "invitee" edge of the TeamInvitation entity.
func (_m *TeamInvitation) QueryInvitee() *UserQuery {
	return NewTeamInvitationClient(_m.config).QueryInvitee(_m)
}

// Update returns a builder for updating this TeamInvitation.
// Note that you need to call TeamInvitation.Unwrap() before calling this method if this TeamInvitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamInvitation) Update() *TeamInvitationUpdateOne {
	return NewTeamInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamInvitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamInvitation) Unwrap() *TeamInvitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamInvitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamInvitation) String() string {
	var builder strings.Builder
	builder.WriteString("TeamInvitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("invitee_email=")
	builder.WriteString(_m.InviteeEmail)
	builder.WriteString(", ")
	if v := _m.InviteeID; v != nil {
		builder.WriteString("invitee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.AcceptanceToken; v != nil {
		builder.WriteString("acceptance_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InviteCode; v != nil {
		builder.WriteString("invite_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenExpiresAt; v != nil {
		builder.WriteString("token_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RespondedAt; v != nil {
		builder.WriteString("responded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TeamInvitations is a parsable slice of TeamInvitation.
type TeamInvitations []*TeamInvitation
