// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/team"
	"taskai/ent/teaminvitation"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamInvitationCreate is the builder for creating a TeamInvitation entity.
type TeamInvitationCreate struct {
	config
	mutation *TeamInvitationMutation
	hooks    []Hook
}

// SetTeamID sets the "team_id" field.
func (_c *TeamInvitationCreate) SetTeamID(v int64) *TeamInvitationCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetInviterID sets the "inviter_id" field.
func (_c *TeamInvitationCreate) SetInviterID(v int64) *TeamInvitationCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeEmail sets the "invitee_email" field.
func (_c *TeamInvitationCreate) SetInviteeEmail(v string) *TeamInvitationCreate {
	_c.mutation.SetInviteeEmail(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *TeamInvitationCreate) SetInviteeID(v int64) *TeamInvitationCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableInviteeID(v *int64) *TeamInvitationCreate {
	if v != nil {
		_c.SetInviteeID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamInvitationCreate) SetStatus(v string) *TeamInvitationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableStatus(v *string) *TeamInvitationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAcceptanceToken sets the "acceptance_token" field.
func (_c *TeamInvitationCreate) SetAcceptanceToken(v string) *TeamInvitationCreate {
	_c.mutation.SetAcceptanceToken(v)
	return _c
}

// SetNillableAcceptanceToken sets the "acceptance_token" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableAcceptanceToken(v *string) *TeamInvitationCreate {
	if v != nil {
		_c.SetAcceptanceToken(*v)
	}
	return _c
}

// SetInviteCode sets the "invite_code" field.
func (_c *TeamInvitationCreate) SetInviteCode(v string) *TeamInvitationCreate {
	_c.mutation.SetInviteCode(v)
	return _c
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableInviteCode(v *string) *TeamInvitationCreate {
	if v != nil {
		_c.SetInviteCode(*v)
	}
	return _c
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_c *TeamInvitationCreate) SetTokenExpiresAt(v time.Time) *TeamInvitationCreate {
	_c.mutation.SetTokenExpiresAt(v)
	return _c
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableTokenExpiresAt(v *time.Time) *TeamInvitationCreate {
	if v != nil {
		_c.SetTokenExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamInvitationCreate) SetCreatedAt(v time.Time) *TeamInvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableCreatedAt(v *time.Time) *TeamInvitationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRespondedAt sets the "responded_at" field.
func (_c *TeamInvitationCreate) SetRespondedAt(v time.Time) *TeamInvitationCreate {
	_c.mutation.SetRespondedAt(v)
	return _c
}

// SetNillableRespondedAt sets the "responded_at" field if the given value is not nil.
func (_c *TeamInvitationCreate) SetNillableRespondedAt(v *time.Time) *TeamInvitationCreate {
	if v != nil {
		_c.SetRespondedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamInvitationCreate) SetID(v int64) *TeamInvitationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamInvitationCreate) SetTeam(v *Team) *TeamInvitationCreate {
	return _c.SetTeamID(v.ID)
}

// SetInviter sets the "inviter" edge to the User entity.
func (_c *TeamInvitationCreate) SetInviter(v *User) *TeamInvitationCreate {
	return _c.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *TeamInvitationCreate) SetInvitee(v *User) *TeamInvitationCreate {
	return _c.SetInviteeID(v.ID)
}

// Mutation returns the TeamInvitationMutation object of the builder.
func (_c *TeamInvitationCreate) Mutation() *TeamInvitationMutation {
	return _c.mutation
}

// Save creates the TeamInvitation in the database.
func (_c *TeamInvitationCreate) Save(ctx context.Context) (*TeamInvitation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamInvitationCreate) SaveX(ctx context.Context) *TeamInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamInvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamInvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamInvitationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := teaminvitation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teaminvitation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamInvitationCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamInvitation.team_id"`)}
	}
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "TeamInvitation.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeEmail(); !ok {
		return &ValidationError{Name: "invitee_email", err: errors.New(`ent: missing required field "TeamInvitation.invitee_email"`)}
	}
	if v, ok := _c.mutation.InviteeEmail(); ok {
		if err := teaminvitation.InviteeEmailValidator(v); err != nil {
			return &ValidationError{Name: "invitee_email", err: fmt.Errorf(`ent: validator failed for field "TeamInvitation.invitee_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeamInvitation.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamInvitation.created_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamInvitation.team"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "TeamInvitation.inviter"`)}
	}
	return nil
}

func (_c *TeamInvitationCreate) sqlSave(ctx context.Context) (*TeamInvitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamInvitationCreate) createSpec() (*TeamInvitation, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamInvitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teaminvitation.Table, sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.InviteeEmail(); ok {
		_spec.SetField(teaminvitation.FieldInviteeEmail, field.TypeString, value)
		_node.InviteeEmail = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teaminvitation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AcceptanceToken(); ok {
		_spec.SetField(teaminvitation.FieldAcceptanceToken, field.TypeString, value)
		_node.AcceptanceToken = &value
	}
	if value, ok := _c.mutation.InviteCode(); ok {
		_spec.SetField(teaminvitation.FieldInviteCode, field.TypeString, value)
		_node.InviteCode = &value
	}
	if value, ok := _c.mutation.TokenExpiresAt(); ok {
		_spec.SetField(teaminvitation.FieldTokenExpiresAt, field.TypeTime, value)
		_node.TokenExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teaminvitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RespondedAt(); ok {
		_spec.SetField(teaminvitation.FieldRespondedAt, field.TypeTime, value)
		_node.RespondedAt = &value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.TeamTable,
			Columns: []string{teaminvitation.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.InviterTable,
			Columns: []string{teaminvitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teaminvitation.InviteeTable,
			Columns: []string{teaminvitation.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamInvitationCreateBulk is the builder for creating many TeamInvitation entities in bulk.
type TeamInvitationCreateBulk struct {
	config
	err      error
	builders []*TeamInvitationCreate
}

// Save creates the TeamInvitation entities in the database.
func (_c *TeamInvitationCreateBulk) Save(ctx context.Context) ([]*TeamInvitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamInvitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamInvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamInvitationCreateBulk) SaveX(ctx context.Context) []*TeamInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamInvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamInvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
