// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/predicate"
	"taskai/ent/wikiblock"
	"taskai/ent/wikipage"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WikiBlockUpdate is the builder for updating WikiBlock entities.
type WikiBlockUpdate struct {
	config
	hooks    []Hook
	mutation *WikiBlockMutation
}

// Where appends a list predicates to the WikiBlockUpdate builder.
func (_u *WikiBlockUpdate) Where(ps ...predicate.WikiBlock) *WikiBlockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPageID sets the "page_id" field.
func (_u *WikiBlockUpdate) SetPageID(v int64) *WikiBlockUpdate {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillablePageID(v *int64) *WikiBlockUpdate {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetBlockType sets the "block_type" field.
func (_u *WikiBlockUpdate) SetBlockType(v string) *WikiBlockUpdate {
	_u.mutation.SetBlockType(v)
	return _u
}

// SetNillableBlockType sets the "block_type" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillableBlockType(v *string) *WikiBlockUpdate {
	if v != nil {
		_u.SetBlockType(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *WikiBlockUpdate) SetLevel(v int) *WikiBlockUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillableLevel(v *int) *WikiBlockUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *WikiBlockUpdate) AddLevel(v int) *WikiBlockUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *WikiBlockUpdate) ClearLevel() *WikiBlockUpdate {
	_u.mutation.ClearLevel()
	return _u
}

// SetHeadingsPath sets the "headings_path" field.
func (_u *WikiBlockUpdate) SetHeadingsPath(v string) *WikiBlockUpdate {
	_u.mutation.SetHeadingsPath(v)
	return _u
}

// SetNillableHeadingsPath sets the "headings_path" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillableHeadingsPath(v *string) *WikiBlockUpdate {
	if v != nil {
		_u.SetHeadingsPath(*v)
	}
	return _u
}

// ClearHeadingsPath clears the value of the "headings_path" field.
func (_u *WikiBlockUpdate) ClearHeadingsPath() *WikiBlockUpdate {
	_u.mutation.ClearHeadingsPath()
	return _u
}

// SetCanonicalJSON sets the "canonical_json" field.
func (_u *WikiBlockUpdate) SetCanonicalJSON(v string) *WikiBlockUpdate {
	_u.mutation.SetCanonicalJSON(v)
	return _u
}

// SetNillableCanonicalJSON sets the "canonical_json" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillableCanonicalJSON(v *string) *WikiBlockUpdate {
	if v != nil {
		_u.SetCanonicalJSON(*v)
	}
	return _u
}

// ClearCanonicalJSON clears the value of the "canonical_json" field.
func (_u *WikiBlockUpdate) ClearCanonicalJSON() *WikiBlockUpdate {
	_u.mutation.ClearCanonicalJSON()
	return _u
}

// SetPlainText sets the "plain_text" field.
func (_u *WikiBlockUpdate) SetPlainText(v string) *WikiBlockUpdate {
	_u.mutation.SetPlainText(v)
	return _u
}

// SetNillablePlainText sets the "plain_text" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillablePlainText(v *string) *WikiBlockUpdate {
	if v != nil {
		_u.SetPlainText(*v)
	}
	return _u
}

// ClearPlainText clears the value of the "plain_text" field.
func (_u *WikiBlockUpdate) ClearPlainText() *WikiBlockUpdate {
	_u.mutation.ClearPlainText()
	return _u
}

// SetPosition sets the "position" field.
func (_u *WikiBlockUpdate) SetPosition(v int) *WikiBlockUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillablePosition(v *int) *WikiBlockUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *WikiBlockUpdate) AddPosition(v int) *WikiBlockUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetSearchText sets the "search_text" field.
func (_u *WikiBlockUpdate) SetSearchText(v string) *WikiBlockUpdate {
	_u.mutation.SetSearchText(v)
	return _u
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (_u *WikiBlockUpdate) SetNillableSearchText(v *string) *WikiBlockUpdate {
	if v != nil {
		_u.SetSearchText(*v)
	}
	return _u
}

// ClearSearchText clears the value of the "search_text" field.
func (_u *WikiBlockUpdate) ClearSearchText() *WikiBlockUpdate {
	_u.mutation.ClearSearchText()
	return _u
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_u *WikiBlockUpdate) SetPage(v *WikiPage) *WikiBlockUpdate {
	return _u.SetPageID(v.ID)
}

// Mutation returns the WikiBlockMutation object of the builder.
func (_u *WikiBlockUpdate) Mutation() *WikiBlockMutation {
	return _u.mutation
}

// ClearPage clears the "page" edge to the WikiPage entity.
func (_u *WikiBlockUpdate) ClearPage() *WikiBlockUpdate {
	_u.mutation.ClearPage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WikiBlockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiBlockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WikiBlockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiBlockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiBlockUpdate) check() error {
	if v, ok := _u.mutation.BlockType(); ok {
		if err := wikiblock.BlockTypeValidator(v); err != nil {
			return &ValidationError{Name: "block_type", err: fmt.Errorf(`ent: validator failed for field "WikiBlock.block_type": %w`, err)}
		}
	}
	if _u.mutation.PageCleared() && len(_u.mutation.PageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiBlock.page"`)
	}
	return nil
}

func (_u *WikiBlockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikiblock.Table, wikiblock.Columns, sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BlockType(); ok {
		_spec.SetField(wikiblock.FieldBlockType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(wikiblock.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(wikiblock.FieldLevel, field.TypeInt, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(wikiblock.FieldLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.HeadingsPath(); ok {
		_spec.SetField(wikiblock.FieldHeadingsPath, field.TypeString, value)
	}
	if _u.mutation.HeadingsPathCleared() {
		_spec.ClearField(wikiblock.FieldHeadingsPath, field.TypeString)
	}
	if value, ok := _u.mutation.CanonicalJSON(); ok {
		_spec.SetField(wikiblock.FieldCanonicalJSON, field.TypeString, value)
	}
	if _u.mutation.CanonicalJSONCleared() {
		_spec.ClearField(wikiblock.FieldCanonicalJSON, field.TypeString)
	}
	if value, ok := _u.mutation.PlainText(); ok {
		_spec.SetField(wikiblock.FieldPlainText, field.TypeString, value)
	}
	if _u.mutation.PlainTextCleared() {
		_spec.ClearField(wikiblock.FieldPlainText, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(wikiblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(wikiblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchText(); ok {
		_spec.SetField(wikiblock.FieldSearchText, field.TypeString, value)
	}
	if _u.mutation.SearchTextCleared() {
		_spec.ClearField(wikiblock.FieldSearchText, field.TypeString)
	}
	if _u.mutation.PageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikiblock.PageTable,
			Columns: []string{wikiblock.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikiblock.PageTable,
			Columns: []string{wikiblock.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikiblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WikiBlockUpdateOne is the builder for updating a single WikiBlock entity.
type WikiBlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WikiBlockMutation
}

// SetPageID sets the "page_id" field.
func (_u *WikiBlockUpdateOne) SetPageID(v int64) *WikiBlockUpdateOne {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillablePageID(v *int64) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetBlockType sets the "block_type" field.
func (_u *WikiBlockUpdateOne) SetBlockType(v string) *WikiBlockUpdateOne {
	_u.mutation.SetBlockType(v)
	return _u
}

// SetNillableBlockType sets the "block_type" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillableBlockType(v *string) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetBlockType(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *WikiBlockUpdateOne) SetLevel(v int) *WikiBlockUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillableLevel(v *int) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *WikiBlockUpdateOne) AddLevel(v int) *WikiBlockUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *WikiBlockUpdateOne) ClearLevel() *WikiBlockUpdateOne {
	_u.mutation.ClearLevel()
	return _u
}

// SetHeadingsPath sets the "headings_path" field.
func (_u *WikiBlockUpdateOne) SetHeadingsPath(v string) *WikiBlockUpdateOne {
	_u.mutation.SetHeadingsPath(v)
	return _u
}

// SetNillableHeadingsPath sets the "headings_path" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillableHeadingsPath(v *string) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetHeadingsPath(*v)
	}
	return _u
}

// ClearHeadingsPath clears the value of the "headings_path" field.
func (_u *WikiBlockUpdateOne) ClearHeadingsPath() *WikiBlockUpdateOne {
	_u.mutation.ClearHeadingsPath()
	return _u
}

// SetCanonicalJSON sets the "canonical_json" field.
func (_u *WikiBlockUpdateOne) SetCanonicalJSON(v string) *WikiBlockUpdateOne {
	_u.mutation.SetCanonicalJSON(v)
	return _u
}

// SetNillableCanonicalJSON sets the "canonical_json" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillableCanonicalJSON(v *string) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetCanonicalJSON(*v)
	}
	return _u
}

// ClearCanonicalJSON clears the value of the "canonical_json" field.
func (_u *WikiBlockUpdateOne) ClearCanonicalJSON() *WikiBlockUpdateOne {
	_u.mutation.ClearCanonicalJSON()
	return _u
}

// SetPlainText sets the "plain_text" field.
func (_u *WikiBlockUpdateOne) SetPlainText(v string) *WikiBlockUpdateOne {
	_u.mutation.SetPlainText(v)
	return _u
}

// SetNillablePlainText sets the "plain_text" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillablePlainText(v *string) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetPlainText(*v)
	}
	return _u
}

// ClearPlainText clears the value of the "plain_text" field.
func (_u *WikiBlockUpdateOne) ClearPlainText() *WikiBlockUpdateOne {
	_u.mutation.ClearPlainText()
	return _u
}

// SetPosition sets the "position" field.
func (_u *WikiBlockUpdateOne) SetPosition(v int) *WikiBlockUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillablePosition(v *int) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *WikiBlockUpdateOne) AddPosition(v int) *WikiBlockUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetSearchText sets the "search_text" field.
func (_u *WikiBlockUpdateOne) SetSearchText(v string) *WikiBlockUpdateOne {
	_u.mutation.SetSearchText(v)
	return _u
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (_u *WikiBlockUpdateOne) SetNillableSearchText(v *string) *WikiBlockUpdateOne {
	if v != nil {
		_u.SetSearchText(*v)
	}
	return _u
}

// ClearSearchText clears the value of the "search_text" field.
func (_u *WikiBlockUpdateOne) ClearSearchText() *WikiBlockUpdateOne {
	_u.mutation.ClearSearchText()
	return _u
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_u *WikiBlockUpdateOne) SetPage(v *WikiPage) *WikiBlockUpdateOne {
	return _u.SetPageID(v.ID)
}

// Mutation returns the WikiBlockMutation object of the builder.
func (_u *WikiBlockUpdateOne) Mutation() *WikiBlockMutation {
	return _u.mutation
}

// ClearPage clears the "page" edge to the WikiPage entity.
func (_u *WikiBlockUpdateOne) ClearPage() *WikiBlockUpdateOne {
	_u.mutation.ClearPage()
	return _u
}

// Where appends a list predicates to the WikiBlockUpdate builder.
func (_u *WikiBlockUpdateOne) Where(ps ...predicate.WikiBlock) *WikiBlockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WikiBlockUpdateOne) Select(field string, fields ...string) *WikiBlockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WikiBlock entity.
func (_u *WikiBlockUpdateOne) Save(ctx context.Context) (*WikiBlock, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiBlockUpdateOne) SaveX(ctx context.Context) *WikiBlock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WikiBlockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiBlockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiBlockUpdateOne) check() error {
	if v, ok := _u.mutation.BlockType(); ok {
		if err := wikiblock.BlockTypeValidator(v); err != nil {
			return &ValidationError{Name: "block_type", err: fmt.Errorf(`ent: validator failed for field "WikiBlock.block_type": %w`, err)}
		}
	}
	if _u.mutation.PageCleared() && len(_u.mutation.PageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiBlock.page"`)
	}
	return nil
}

func (_u *WikiBlockUpdateOne) sqlSave(ctx context.Context) (_node *WikiBlock, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikiblock.Table, wikiblock.Columns, sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WikiBlock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wikiblock.FieldID)
		for _, f := range fields {
			if !wikiblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wikiblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BlockType(); ok {
		_spec.SetField(wikiblock.FieldBlockType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(wikiblock.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(wikiblock.FieldLevel, field.TypeInt, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(wikiblock.FieldLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.HeadingsPath(); ok {
		_spec.SetField(wikiblock.FieldHeadingsPath, field.TypeString, value)
	}
	if _u.mutation.HeadingsPathCleared() {
		_spec.ClearField(wikiblock.FieldHeadingsPath, field.TypeString)
	}
	if value, ok := _u.mutation.CanonicalJSON(); ok {
		_spec.SetField(wikiblock.FieldCanonicalJSON, field.TypeString, value)
	}
	if _u.mutation.CanonicalJSONCleared() {
		_spec.ClearField(wikiblock.FieldCanonicalJSON, field.TypeString)
	}
	if value, ok := _u.mutation.PlainText(); ok {
		_spec.SetField(wikiblock.FieldPlainText, field.TypeString, value)
	}
	if _u.mutation.PlainTextCleared() {
		_spec.ClearField(wikiblock.FieldPlainText, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(wikiblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(wikiblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchText(); ok {
		_spec.SetField(wikiblock.FieldSearchText, field.TypeString, value)
	}
	if _u.mutation.SearchTextCleared() {
		_spec.ClearField(wikiblock.FieldSearchText, field.TypeString)
	}
	if _u.mutation.PageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikiblock.PageTable,
			Columns: []string{wikiblock.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikiblock.PageTable,
			Columns: []string{wikiblock.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WikiBlock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikiblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
