// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/user"
	"taskai/ent/wikipage"
	"taskai/ent/wikipageversion"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WikiPageVersionCreate is the builder for creating a WikiPageVersion entity.
type WikiPageVersionCreate struct {
	config
	mutation *WikiPageVersionMutation
	hooks    []Hook
}

// SetWikiPageID sets the "wiki_page_id" field.
func (_c *WikiPageVersionCreate) SetWikiPageID(v int64) *WikiPageVersionCreate {
	_c.mutation.SetWikiPageID(v)
	return _c
}

// SetVersionNumber sets the "version_number" field.
func (_c *WikiPageVersionCreate) SetVersionNumber(v int) *WikiPageVersionCreate {
	_c.mutation.SetVersionNumber(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *WikiPageVersionCreate) SetContent(v string) *WikiPageVersionCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableContent(v *string) *WikiPageVersionCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *WikiPageVersionCreate) SetContentHash(v string) *WikiPageVersionCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *WikiPageVersionCreate) SetCreatedBy(v int64) *WikiPageVersionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WikiPageVersionCreate) SetCreatedAt(v time.Time) *WikiPageVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableCreatedAt(v *time.Time) *WikiPageVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WikiPageVersionCreate) SetID(v int64) *WikiPageVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetWikiPage sets the "wiki_page" edge to the WikiPage entity.
func (_c *WikiPageVersionCreate) SetWikiPage(v *WikiPage) *WikiPageVersionCreate {
	return _c.SetWikiPageID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *WikiPageVersionCreate) SetCreatorID(id int64) *WikiPageVersionCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *WikiPageVersionCreate) SetCreator(v *User) *WikiPageVersionCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the WikiPageVersionMutation object of the builder.
func (_c *WikiPageVersionCreate) Mutation() *WikiPageVersionMutation {
	return _c.mutation
}

// Save creates the WikiPageVersion in the database.
func (_c *WikiPageVersionCreate) Save(ctx context.Context) (*WikiPageVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WikiPageVersionCreate) SaveX(ctx context.Context) *WikiPageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WikiPageVersionCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := wikipageversion.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wikipageversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WikiPageVersionCreate) check() error {
	if _, ok := _c.mutation.WikiPageID(); !ok {
		return &ValidationError{Name: "wiki_page_id", err: errors.New(`ent: missing required field "WikiPageVersion.wiki_page_id"`)}
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		return &ValidationError{Name: "version_number", err: errors.New(`ent: missing required field "WikiPageVersion.version_number"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "WikiPageVersion.content"`)}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "WikiPageVersion.content_hash"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := wikipageversion.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "WikiPageVersion.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "WikiPageVersion.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WikiPageVersion.created_at"`)}
	}
	if len(_c.mutation.WikiPageIDs()) == 0 {
		return &ValidationError{Name: "wiki_page", err: errors.New(`ent: missing required edge "WikiPageVersion.wiki_page"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "WikiPageVersion.creator"`)}
	}
	return nil
}

func (_c *WikiPageVersionCreate) sqlSave(ctx context.Context) (*WikiPageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WikiPageVersionCreate) createSpec() (*WikiPageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &WikiPageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wikipageversion.Table, sqlgraph.NewFieldSpec(wikipageversion.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.VersionNumber(); ok {
		_spec.SetField(wikipageversion.FieldVersionNumber, field.TypeInt, value)
		_node.VersionNumber = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(wikipageversion.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(wikipageversion.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wikipageversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.WikiPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.WikiPageTable,
			Columns: []string{wikipageversion.WikiPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WikiPageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.CreatorTable,
			Columns: []string{wikipageversion.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WikiPageVersionCreateBulk is the builder for creating many WikiPageVersion entities in bulk.
type WikiPageVersionCreateBulk struct {
	config
	err      error
	builders []*WikiPageVersionCreate
}

// Save creates the WikiPageVersion entities in the database.
func (_c *WikiPageVersionCreateBulk) Save(ctx context.Context) ([]*WikiPageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WikiPageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WikiPageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WikiPageVersionCreateBulk) SaveX(ctx context.Context) []*WikiPageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
