// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/user"
	"taskai/ent/wikipage"
	"taskai/ent/yjsupdate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// YjsUpdateCreate is the builder for creating a YjsUpdate entity.
type YjsUpdateCreate struct {
	config
	mutation *YjsUpdateMutation
	hooks    []Hook
}

// SetPageID sets the "page_id" field.
func (_c *YjsUpdateCreate) SetPageID(v int64) *YjsUpdateCreate {
	_c.mutation.SetPageID(v)
	return _c
}

// SetUpdateData sets the "update_data" field.
func (_c *YjsUpdateCreate) SetUpdateData(v []byte) *YjsUpdateCreate {
	_c.mutation.SetUpdateData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *YjsUpdateCreate) SetCreatedAt(v time.Time) *YjsUpdateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *YjsUpdateCreate) SetNillableCreatedAt(v *time.Time) *YjsUpdateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *YjsUpdateCreate) SetCreatedBy(v int64) *YjsUpdateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *YjsUpdateCreate) SetNillableCreatedBy(v *int64) *YjsUpdateCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *YjsUpdateCreate) SetID(v int64) *YjsUpdateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPage sets the "page" edge to the WikiPage entity.
func (_c *YjsUpdateCreate) SetPage(v *WikiPage) *YjsUpdateCreate {
	return _c.SetPageID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *YjsUpdateCreate) SetCreatorID(id int64) *YjsUpdateCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_c *YjsUpdateCreate) SetNillableCreatorID(id *int64) *YjsUpdateCreate {
	if id != nil {
		_c = _c.SetCreatorID(*id)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *YjsUpdateCreate) SetCreator(v *User) *YjsUpdateCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the YjsUpdateMutation object of the builder.
func (_c *YjsUpdateCreate) Mutation() *YjsUpdateMutation {
	return _c.mutation
}

// Save creates the YjsUpdate in the database.
func (_c *YjsUpdateCreate) Save(ctx context.Context) (*YjsUpdate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *YjsUpdateCreate) SaveX(ctx context.Context) *YjsUpdate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YjsUpdateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YjsUpdateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *YjsUpdateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := yjsupdate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *YjsUpdateCreate) check() error {
	if _, ok := _c.mutation.PageID(); !ok {
		return &ValidationError{Name: "page_id", err: errors.New(`ent: missing required field "YjsUpdate.page_id"`)}
	}
	if _, ok := _c.mutation.UpdateData(); !ok {
		return &ValidationError{Name: "update_data", err: errors.New(`ent: missing required field "YjsUpdate.update_data"`)}
	}
	if v, ok := _c.mutation.UpdateData(); ok {
		if err := yjsupdate.UpdateDataValidator(v); err != nil {
			return &ValidationError{Name: "update_data", err: fmt.Errorf(`ent: validator failed for field "YjsUpdate.update_data": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "YjsUpdate.created_at"`)}
	}
	if len(_c.mutation.PageIDs()) == 0 {
		return &ValidationError{Name: "page", err: errors.New(`ent: missing required edge "YjsUpdate.page"`)}
	}
	return nil
}

func (_c *YjsUpdateCreate) sqlSave(ctx context.Context) (*YjsUpdate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *YjsUpdateCreate) createSpec() (*YjsUpdate, *sqlgraph.CreateSpec) {
	var (
		_node = &YjsUpdate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(yjsupdate.Table, sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UpdateData(); ok {
		_spec.SetField(yjsupdate.FieldUpdateData, field.TypeBytes, value)
		_node.UpdateData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(yjsupdate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   yjsupdate.PageTable,
			Columns: []string{yjsupdate.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   yjsupdate.CreatorTable,
			Columns: []string{yjsupdate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// YjsUpdateCreateBulk is the builder for creating many YjsUpdate entities in bulk.
type YjsUpdateCreateBulk struct {
	config
	err      error
	builders []*YjsUpdateCreate
}

// Save creates the YjsUpdate entities in the database.
func (_c *YjsUpdateCreateBulk) Save(ctx context.Context) ([]*YjsUpdate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*YjsUpdate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*YjsUpdateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *YjsUpdateCreateBulk) SaveX(ctx context.Context) []*YjsUpdate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YjsUpdateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YjsUpdateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
